"""todo

Revision ID: 578ad80e3ef1
Revises: 2981f158241e
Create Date: 2024-04-19 18:37:24.061505

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '578ad80e3ef1'
down_revision: Union[str, None] = '2981f158241e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('genero',
    sa.Column('genero_id', sa.Integer(), nullable=False),
    sa.Column('nombre_genero', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('genero_id')
    )
    op.create_table('pelicula',
    sa.Column('pelicula_id', sa.Integer(), nullable=False),
    sa.Column('titulo', sa.String(), nullable=False),
    sa.Column('sinopsis', sa.String(), nullable=True),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('link', sa.String(), nullable=True),
    sa.Column('genero', sa.ARRAY(sa.Integer()), nullable=True),
    sa.PrimaryKeyConstraint('pelicula_id'),
    sa.UniqueConstraint('pelicula_id')
    )
    op.create_table('peli_user',
    sa.Column('persona_id_2', sa.Integer(), nullable=False),
    sa.Column('pelicula_id_2', sa.Integer(), nullable=False),
    sa.Column('comentario', sa.String(), nullable=True),
    sa.Column('calificacion', sa.Integer(), nullable=True),
    sa.Column('estado', sa.Boolean(), nullable=False),
    sa.Column('fecha_vista', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['pelicula_id_2'], ['pelicula.pelicula_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['persona_id_2'], ['persona.persona_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('persona_id_2', 'pelicula_id_2')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('peli_user')
    op.drop_table('pelicula')
    op.drop_table('genero')
    # ### end Alembic commands ###
